PROJ = diff_ext1058.dll
!ifndef ROOT
ROOT = ..\..
!endif

DEF=diff_ext.def
OBJ=diff_ext.res
    
!include $(ROOT)\make\resource-library.mak

# any modifications to the flags should go _after_ win32.mak
rcflags = $(rcflags) -I..\..\include

#dependency information goes here
